<?php
 // Dirs
$RootFolder = "././";
$ResourcesFolder = $RootFolder . "Resources/";
$ResourcesCSSFolder = $ResourcesFolder . "CSS/";
$ResourcesJSONFolder = $ResourcesFolder . "JSON/";
$ModulesFolder = $RootFolder . "Modules/";
$PHPModulesFolder = $ModulesFolder . "PHP/";
$JavaScriptModulesFolder = $ModulesFolder . "JavaScript/";

// Modules
require_once($PHPModulesFolder . "Debug.php");
require_once($PHPModulesFolder . "Shortcuts.php");

// CORE
$Debug = new Debug();
$Shortcuts = new Shortcuts();

$CoreJSONFile = file_get_contents($ResourcesJSONFolder . "Core.json");
$IconsJSONFile = file_get_contents($ResourcesJSONFolder . "Icons.json");

$CoreInfo = json_decode($CoreJSONFile, false);
$IconsInfo = json_decode($IconsJSONFile, false);
?>

<head>
    <meta charset="utf-8">
    <link rel="shortcut icon" type="image/x-icon" href= "<?php echo $RootFolder . "favicon.ico" ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href=<?php echo $ResourcesCSSFolder . "ColourSheet.css"?>>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/97f53ab0cf.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="<?php echo $JavaScriptModulesFolder . "qrcode.js"  ?> "></script>
</head>

<body>
    <?php
        $Debug->Log("Header.phtml | Stage 1");
        if ((isset($_SESSION["Cookies"])) and isset($_SESSION["Account"]))
        {
            if ($_SESSION["Cookies"])
            {
                $Debug->Log("Header.phtml | Storing account cookie info");
                try
                {
                    if (!isset($_COOKIE["Token"]) or ($_COOKIE["Token"] !== $_SESSION["Account"]["Token"]))
                    {
                        setcookie("Username", $_SESSION["Account"]["Username"], time() + $Shortcuts->DaysToSeconds(5), "/"); //$Shortcuts->GetRoot());
                        setcookie("Token", $_SESSION["Account"]["Token"], time() + $Shortcuts->DaysToSeconds(5), "/"); //$Shortcuts->GetRoot());
                    }

                }
                catch (Exception $e)
                {
                    $Debug->Log("Header.phtml | Error: " . $e->getMessage());
                }

            }
            else
            {
                $Debug->Log("Header.phtml | Removing account cookie info");
                $ToUnset = array("Username", "Token");

                foreach($ToUnset as &$CookieName)
                {
                    $Shortcuts->RemoveCookie($CookieName);
                }
            }

        }
    ?>

    <div class="modal fade" id="LogoutModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirm Logout</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <p>Are you sure you want to log out?</p>
                </div>

                <div class="modal-footer">
                    <form action="Login.php" method="POST">
                        <input type="hidden" name="ClientRequest" value = "Logout">
                        <input id="ConfirmLogoutButton" type="submit" class="btn btn-danger" value="Logout">
                    </form>

                    <script>
                        let ConfirmLogoutButton = document.getElementById("ConfirmLogoutButton");

                        ConfirmLogoutButton.onclick(function() {
                           document.cookie = "Token=; Max-Age=-99999999;";
                           document.cookie = "Username=; Max-Age=-99999999;";
                        });
                    </script>


                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="display: inline-block">Close</button>
                </div>
            </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="z-index: 50">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="Login.php"><?php echo $View->CoreInfo->SiteName ?></a>
            </div>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="float: left">
                <li class="nav-item"><form action="Login.php" method="POST" class="form-inline my-2 my-lg-0">
                        <?php
                        $ClientRequest = "";

                        if (!isset($_SESSION["LoggedIn"]))
                        {
                            $ClientRequest = "Login";
                        }
                        else
                        {
                            $ClientRequest = "Logout";
                        }
                        ?>
                        <input type="hidden" name="ClientRequest" value = <?php global $ClientRequest; echo $ClientRequest ?>>

                        <?php
                            if ($ClientRequest == "Logout")
                            {
                                echo "<input type='button' class='nav-link' value='" . $ClientRequest . "' style='border-width: 0; background-color: transparent;' data-bs-toggle='modal' data-bs-target='#LogoutModal'>";
                            }
                            else
                            {
                                echo "<input type='submit' class='nav-link' value='" . $ClientRequest . "' style='border-width: 0; background-color: transparent;'>";
                            }
                        ?>

                    </form></li>

                <?php
                    foreach($CoreInfo->TopBar as $TopbarName => $Info)
                    {
                        if (isset($Info->LoggedIn) and $Info->LoggedIn)
                        {
                            if (!isset($_SESSION["LoggedIn"]) or !$_SESSION["LoggedIn"])
                            {
                                continue;
                            }
                        }

                        if (isset($Info->Hidden) and $Info->Hidden)
                        {
                            continue;
                        }

                        $Dir = $RootFolder . $TopbarName . ".php";
                        echo "<li class='nav-item'><a class='nav-link' href='$Dir' style='float: " . $Info->float .  ";'>"; //$TopbarName</a></li>";

                        //var_dump($Info);

                        if (isset($Info->Icon))
                        {
                            echo $IconsInfo->{$Info->Icon};
                        }
                        else
                        {
                            echo $TopbarName;
                        }

                        echo "</a></li>";
                    }
                ?>

                <!--<li class="nav-item"><a class="nav-link" href=<?php //echo $RootFolder . "Home.php" ?>>Home</a></li>-->
            </ul>

            <div class="navbar-header text-center" style="/*right: 10px;*/ float: right;">
                <?php
                    if (isset($_SESSION["LoggedIn"]))
                    {
                        echo "<span style='margin: 10px;'><strong>Role: " . $_SESSION["Account"]["UserType"] . "</strong></span>";

                        $Dir = $RootFolder . "Profile.php";
                        echo "<a class='' href='$Dir' style='float: right; display: inline; text-decoration: none;'>" . $IconsInfo->{$CoreInfo->TopBar->Profile->Icon} . "</a>";
                    }
                ?>
            </div>
        </div>
    </nav>

    <?php
        if (isset($View->LoadAlert))
        {
            echo '<div class="alert alert-' . $View->LoadAlert->Type . ' alert-dismissible fade show mx-auto text-center" role="alert" style="width:100% border-radius: 0;">';
                echo '<strong>' . $View->LoadAlert->Message . '</strong>';

                echo '<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">';
                    echo '<span aria-hidden="true">&times;</span>';
                echo '</button>';
            echo '</div>';
        }
    ?>

</body>